/* eslint-disable no-console */
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

function getGitSha() {
  try {
    return execSync("git rev-parse --short HEAD", { stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return "unknown";
  }
}

function pad2(n) {
  return String(n).padStart(2, "0");
}

function formatDate(d) {
  return `${d.getFullYear()}.${pad2(d.getMonth() + 1)}.${pad2(d.getDate())}`;
}

function main() {
  const sha = getGitSha();
  const date = formatDate(new Date());
  const version = `${date}+${sha}`;

  const outPath = path.join(__dirname, "..", "src", "version.ts");
  const content =
    `// Auto-generated by frontend/scripts/write-version.js\n` +
    `// Update trigger: git commit / deploy\n` +
    `export const APP_VERSION = ${JSON.stringify(version)};\n`;

  const prev = fs.existsSync(outPath) ? fs.readFileSync(outPath, "utf8") : "";
  if (prev === content) {
    return;
  }
  fs.writeFileSync(outPath, content);
  console.log(`[version] wrote ${outPath}: ${version}`);
}

main();


