/* eslint-disable no-console */
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

function getGitSha() {
  try {
    return execSync("git rev-parse --short HEAD", { stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return "unknown";
  }
}

function getGitCommitCount() {
  try {
    return execSync("git rev-list --count HEAD", { stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return "0";
  }
}

function main() {
  const count = getGitCommitCount();
  const sha = getGitSha();
  // 要件: 1日に複数回更新されるため、日付ではなく単調増加の番号にする
  // 追跡しやすいよう sha もコメントに残す（表示は番号のみ）
  const version = `v${count}`;

  const outPath = path.join(__dirname, "..", "src", "version.ts");
  const content =
    `// Auto-generated by frontend/scripts/write-version.js\n` +
    `// Update trigger: git commit / deploy\n` +
    `// Source: git rev-list --count HEAD (sha: ${sha})\n` +
    `export const APP_VERSION = ${JSON.stringify(version)};\n`;

  const prev = fs.existsSync(outPath) ? fs.readFileSync(outPath, "utf8") : "";
  if (prev === content) {
    return;
  }
  fs.writeFileSync(outPath, content);
  console.log(`[version] wrote ${outPath}: ${version}`);
}

main();



